server:
  port: 8090
spring:
  application:
    name: payment-service
  config:
    import: "configserver:http://localhost:8888"
  profiles:
    active: dev

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

logging:
  level:
    org:
      springframework:
        cloud: DEBUG
      boot:
        context:
          config: DEBUG